name: Tweet at Midnight JST

on:
  schedule:
    - cron: '0 15 * * *'  # JST 0:00（UTC 15:00）

  workflow_dispatch:  # 手動実行を可能にする
  
jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v4

    - name: Python をセットアップ
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: 依存関係をインストール
      run: pip install tweepy pytz  # ここで pytz も一緒にインストールする

    - name: Twitter に投稿
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET: ${{ secrets.API_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      run: python tweet.py
